package:
  format-version: "1.0.0"
  name: "wireless_15_4_phy"
  type: "package"
  status: "production"
  required: false
  version: "1.1.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "bsp"
      type: "package"
      version: "v3.16.0"
    - name: "core"
      type: "package"
      version: "v3.13.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.2.0" 